[package]
name = "news-letter"
version = "0.1.0"
authors = ["Hunter, Christerpher <djhunter67@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.5.1"
